import type { Metadata } from "next";
import "./globals.css";
import {Header} from "@/components/Header";
import {montserrat} from "@/utils/fonts";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="ro"
            className={`${montserrat.className} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <Header/>
                {children}
                <Footer/>
            </body>
        </html>
    );
}
